{% set version = "0.1.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gsmoothr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gsmoothr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gsmoothr/gsmoothr_{{ version }}.tar.gz
  sha256: b75ffd2a4a0f357762e02e46e355b45cc90ea637830f0a1b01f216bb4541e903

build:
  number: 1007
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('gsmoothr')"           # [not win]
    - "\"%R%\" -e \"library('gsmoothr')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gsmoothr
  license: LGPL-2.0-or-later
  summary: Tools rewritten in C for various smoothing tasks
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
