appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: nE0gl3dCTeOvEOlOiaJDnNtpdnGDFh3eKZonJrgypvwnxYGoj83B7KPU9rY9Pb0L6qTRfKzfK/zsP42kI25E1VKSEm7KgLRD8vY4p7hvHMPfY5BLYVVz0B0U6Laow/mqW2hmMOVHrmbjhUjToVLigMdgGpKaXVZ01uSnRHAwSOHX8BmDdHQVmsq4axUMUX3PpzjLrvtw+FV5xRrbwQCmfalZzU4MMTsrCVK4XzYVKfJ2I74EOGrJs9VPecdKzFrEQ6usIT9lqI/WGqyHDuMDpigAy/2i1yFwZSmWHuKmmDIgPdtOKiEJQIkrV0Ikv1tYRTVGnhoRAhzL7sRO41MAh2D16FJ1Vn5v0LglhwPJ4vAINefgApGx4genu1WsFFAFDqOG521dkg3IhGpHvYGLQUl5ywC5TD02kf4Qy21MpXEuvPjwyti4ACfnuNzyYhO1M2ZDXMMldSu3Glu9puHvvXcN7flBtTxNkHw+9aAQOvs2jVtijrwFR14Mn7FQEtGWKZyU+tmuGNtZgP0875iYZVSYbaaq7gau94JLFZ/NnU5GBXXS/My884y7LwXOK+kt0ErsCGxQMw9MBGGSuzClMdau6SNQnR+f3n9zUdBHxyO9TVmv1Z7GssfsKFZJYZxYrDQuSSMHjDkc3zgmPFHcbbh8ZxuDh5iHLCT0XGDYoyo=}
